version: '3.8'

services:


  manager:
    build:
      context: ..
    container_name: manager
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      rabbitmq1:
        condition: service_healthy

  worker1:
    build:
      context: ../../worker
    container_name: worker1
    ports:
      - "8081:8080"
    restart: always
    networks:
      - app-network
    environment:
      - SERVER_PORT=8080
      - REQUEST_QUEUE=request_queue_1
    depends_on:
      rabbitmq1:
        condition: service_healthy

  rabbitmq1:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq2:
    image: rabbitmq:management
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge




